// <auto-generated />
namespace UniversityCF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class enablestundentstable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(enablestundentstable));
        
        string IMigrationMetadata.Id
        {
            get { return "202110300231520_enable-stundents-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
